### ISSUE TITLE
Add example ENV file

### ISSUE THREAD

**Issue by itzsaga** [nashvillefcc/wise-guys-qr#5]
Add a `.env.example` to the root of the project so people know which key values they need in their `.env` file.

Current keys needed are:
- [ ] GATSBY_AUTH0_DOMAIN
- [ ] GATSBY_AUTH0_CLIENTID
- [ ] GATSBY_AUTH0_CALLBACK

**Comment by Hekotoru** [comment]
Hi @itzsaga I'll do it  😄

**Comment by itzsaga** [comment]
Thanks @Hekotoru !
